application:
  version: @project.version@
  title: @project.name@

logging:
  level:
    root: INFO

spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:file:./data/gamedatabase
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect